// M4 DoD: "manual smoke test against real Drive with the test graph". A scripted run of the Drive layer
// inside Logseq, started from the demo controls: it creates a throwaway root folder
// "<rootFolderName> smoke-<time>", exercises the layout bootstrap, both upload protocols, downloads,
// appProperties, listing, changes and the lock, then deletes that folder again. On failure the folder is
// left in Drive for inspection and the report says so. Lives in src/mock/ (deleted in M7).
//
// The only graph access is READING one binary asset (the largest png/pdf/jpg) for the resumable upload,
// and only when the current graph lives under ~/logseq-test-graphs/ (D11); otherwise the run refuses.

import { sha256Hex } from '../fs/hash'
import { fetchAccount } from '../google/account'
import type { GoogleAuth } from '../google/auth'
import { createDriveClient, isNotFound, type DriveClient, type DriveFile } from '../google/drive'
import { RESUMABLE_CHUNK_UNIT } from '../google/driveUpload'
import { describeGoogleError } from '../google/errors'
import type { FetchLike } from '../google/http'
import { bootstrapLayout, type DriveLayout } from '../google/layout'
import { LOCK_FILE, createDriveLock } from '../google/lock'
import { createHostDriveClient } from '../logseq/googleHost'

export interface SmokeReport {
  passed: number
  total: number
  failedStep: string | null
  error: string | null
  /** The Drive folder left behind after a failure, for inspection. */
  leftoverFolder: string | null
  durationMs: number
}

export interface SmokeDeps {
  auth: GoogleAuth
  rootFolderName: string
  graph: { name: string; path: string } | null
  log: (line: string, detail?: unknown) => void
  onStep: (label: string, index: number, total: number) => void
}

const TEST_GRAPH_MARKER = '/logseq-test-graphs/'
/** Small thresholds so a 3 MB asset takes the resumable path with several chunks. */
const SMOKE_MULTIPART_MAX = 512 * 1024
const SMOKE_CHUNK = 4 * RESUMABLE_CHUNK_UNIT
const GENERATED_ASSET_BYTES = 2_621_440 + 1

function stamp(d: Date): string {
  const p = (n: number): string => String(n).padStart(2, '0')
  return `${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`
}

function randomBytes(n: number): Uint8Array<ArrayBuffer> {
  const out = new Uint8Array(n)
  for (let at = 0; at < n; at += 65_536) crypto.getRandomValues(out.subarray(at, Math.min(n, at + 65_536)))
  return out
}

async function pickAsset(log: SmokeDeps['log']): Promise<{ name: string; bytes: Uint8Array<ArrayBuffer>; source: string }> {
  try {
    const assets = await logseq.Assets.listFilesOfCurrentGraph(['png', 'pdf', 'jpg', 'jpeg'])
    const largest = [...assets].sort((a, b) => b.size - a.size)[0]
    if (largest && largest.size >= 2 * SMOKE_CHUNK) {
      const res = await fetch(`file://${encodeURI(largest.path)}`)
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const bytes = new Uint8Array(await res.arrayBuffer())
      return { name: largest.path.split('/').pop() ?? 'asset.bin', bytes, source: `graph asset ${largest.path} (${bytes.byteLength} bytes)` }
    }
  } catch (err) {
    log('reading a graph asset failed; using generated bytes', err)
  }
  return { name: 'generated-noise.bin', bytes: randomBytes(GENERATED_ASSET_BYTES), source: `generated ${GENERATED_ASSET_BYTES} random bytes` }
}

export async function runDriveSmoke(deps: SmokeDeps): Promise<SmokeReport> {
  const startedAt = Date.now()
  const { log } = deps
  if (!deps.graph || !deps.graph.path.includes(TEST_GRAPH_MARKER)) {
    return {
      passed: 0,
      total: 0,
      failedStep: 'preflight',
      error: `The smoke test only runs with a graph under ~${TEST_GRAPH_MARKER} open (D11); current: ${deps.graph?.path ?? 'none'}.`,
      leftoverFolder: null,
      durationMs: Date.now() - startedAt,
    }
  }
  const graphName = deps.graph.name
  const rootName = `${deps.rootFolderName} smoke-${stamp(new Date(startedAt))}`
  const deviceId = crypto.randomUUID()

  let requestCount = 0
  const countingFetch: FetchLike = (url, init) => {
    requestCount++
    return deps.auth.fetch(url, init)
  }
  const client: DriveClient = createDriveClient({
    fetch: countingFetch,
    log: (line) => log(`drive: ${line}`),
    multipartMaxBytes: SMOKE_MULTIPART_MAX,
    chunkBytes: SMOKE_CHUNK,
  })

  const steps: Array<[string, () => Promise<string>]> = []
  const step = (name: string, run: () => Promise<string>): void => {
    steps.push([name, run])
  }

  // Shared state between steps.
  let layout: DriveLayout | null = null
  let startToken = ''
  let mdFile: DriveFile | null = null
  let mdText = ''
  let mdSha = ''
  let asset: Awaited<ReturnType<typeof pickAsset>> | null = null
  let assetFile: DriveFile | null = null
  let rootCreated = false

  step('about.get', async () => {
    const account = await fetchAccount(countingFetch)
    return `signed in as ${account.email}`
  })

  step('bootstrap layout (twice)', async () => {
    layout = await bootstrapLayout(client, { rootFolderName: rootName, graphName })
    rootCreated = true
    const before = requestCount
    const again = await bootstrapLayout(client, { rootFolderName: rootName, graphName })
    if (JSON.stringify(again) !== JSON.stringify(layout)) throw new Error('second bootstrap returned different ids')
    if (requestCount !== before) throw new Error(`second bootstrap made ${requestCount - before} requests; expected 0 (cache)`)
    return `root ${layout.rootId}, graph folder ${layout.graphFolderId}; second call served from the cache`
  })

  step('changes.getStartPageToken', async () => {
    startToken = await client.getStartPageToken()
    return `token ${startToken}`
  })

  step('multipart upload (pages/smoke.md)', async () => {
    const pagesId = await client.ensureFolder(layout!.graphFolderId, 'pages')
    mdText = `# Smoke\n\nWritten at ${new Date(startedAt).toISOString()} by ${deviceId}.\n`
    mdSha = await sha256Hex(mdText)
    mdFile = await client.createFile(mdText, { name: 'smoke.md', parentId: pagesId, mimeType: 'text/markdown', appProperties: { sha256: mdSha, relPath: 'pages/smoke.md', deviceId }, modifiedTime: startedAt - 60_000 })
    if (mdFile.size !== new TextEncoder().encode(mdText).byteLength) throw new Error(`size ${mdFile.size} does not match`)
    if (mdFile.appProperties.sha256 !== mdSha || mdFile.appProperties.relPath !== 'pages/smoke.md') throw new Error('appProperties not echoed back')
    if (Math.abs(mdFile.modifiedTime - (startedAt - 60_000)) > 1000) throw new Error(`modifiedTime not honoured (${new Date(mdFile.modifiedTime).toISOString()})`)
    return `id ${mdFile.id}, ${mdFile.size} bytes, md5 ${mdFile.md5Checksum}`
  })

  step('resumable upload (assets/…)', async () => {
    asset = await pickAsset(log)
    const assetsId = await client.ensureFolder(layout!.graphFolderId, 'assets')
    const sha = await sha256Hex(asset.bytes)
    const chunks: number[] = []
    const t = Date.now()
    assetFile = await client.createFile(asset.bytes, { name: asset.name, parentId: assetsId, mimeType: 'application/octet-stream', appProperties: { sha256: sha, relPath: `assets/${asset.name}`, deviceId } }, { onProgress: (done) => chunks.push(done) })
    if (assetFile.size !== asset.bytes.byteLength) throw new Error(`size ${assetFile.size} does not match ${asset.bytes.byteLength}`)
    return `${asset.source} → id ${assetFile.id} in ${Date.now() - t} ms; progress ${chunks.join(' → ')}`
  })

  step('download + SHA-256 compare', async () => {
    const t = Date.now()
    const text = await client.downloadText(mdFile!.id)
    if (text !== mdText) throw new Error('markdown content differs after download')
    const bytes = await client.download(assetFile!.id)
    if ((await sha256Hex(bytes)) !== (await sha256Hex(asset!.bytes))) throw new Error('asset hash differs after download')
    return `both files match (${bytes.byteLength + text.length} bytes in ${Date.now() - t} ms)`
  })

  step('appProperties patch + query', async () => {
    const patched = await client.updateMetadata(mdFile!.id, { appProperties: { deviceId: null, note: 'patched' } })
    if (patched.appProperties.deviceId !== undefined) throw new Error('deviceId key was not deleted')
    if (patched.appProperties.note !== 'patched' || patched.appProperties.sha256 !== mdSha) throw new Error(`merge wrong: ${JSON.stringify(patched.appProperties)}`)
    const found = await client.findByAppProperty('sha256', mdSha)
    if (!found.some((f) => f.id === mdFile!.id)) throw new Error('query by appProperties did not find the file')
    return `merged keys ${Object.keys(patched.appProperties).join(', ')}; query found ${found.length} file(s)`
  })

  step('update content (multipart PATCH)', async () => {
    mdText += '\n- second line\n'
    mdSha = await sha256Hex(mdText)
    const updated = await client.updateFile(mdFile!.id, new Blob([mdText], { type: 'text/markdown' }), { appProperties: { sha256: mdSha } })
    if (updated.id !== mdFile!.id) throw new Error('update changed the file id')
    if ((await client.downloadText(mdFile!.id)) !== mdText) throw new Error('content differs after update')
    mdFile = updated
    return `now ${updated.size} bytes, sha256 tag ${updated.appProperties.sha256?.slice(0, 12)}…`
  })

  step('listTree + pathUnder', async () => {
    const tree = await client.listTree(layout!.graphFolderId)
    const paths = tree.map((e) => e.segments.join('/')).sort()
    const expected = ['assets', `assets/${asset!.name}`, 'pages', 'pages/smoke.md']
    if (JSON.stringify(paths) !== JSON.stringify(expected)) throw new Error(`tree ${JSON.stringify(paths)} ≠ ${JSON.stringify(expected)}`)
    const fresh = createHostDriveClient(deps.auth)
    const segments = await fresh.pathUnder(await fresh.getFile(mdFile!.id), layout!.graphFolderId)
    if (segments?.join('/') !== 'pages/smoke.md') throw new Error(`pathUnder gave ${JSON.stringify(segments)}`)
    return `${tree.length} entries: ${paths.join(', ')}`
  })

  step('changes.list', async () => {
    const result = await client.listChanges(startToken)
    const ids = new Set(result.changes.map((c) => c.fileId))
    if (!ids.has(mdFile!.id) || !ids.has(assetFile!.id)) throw new Error(`changes miss our files (${result.changes.length} entries)`)
    const second = await client.listChanges(result.newStartPageToken)
    if (second.changes.length !== 0) throw new Error(`${second.changes.length} unexpected changes after the new token`)
    return `${result.changes.length} changes since ${startToken}; new token ${result.newStartPageToken}; none after it`
  })

  step('lock: acquire / held / renew / release / break-expired', async () => {
    const mk = (id: string, name: string) => createDriveLock({ client, graphFolderId: layout!.graphFolderId, deviceId: id, deviceName: name, log: (l) => log(`lock: ${l}`) })
    const a = mk(deviceId, 'smoke-A')
    const b = mk(crypto.randomUUID(), 'smoke-B')
    const r1 = await a.acquire({ ttlMs: 60_000 })
    if (r1.kind !== 'acquired') throw new Error(`A could not acquire: ${JSON.stringify(r1)}`)
    const r2 = await b.acquire({ ttlMs: 60_000 })
    if (r2.kind !== 'held' || r2.expired || r2.lock.deviceName !== 'smoke-A') throw new Error(`B should see A's live lock: ${JSON.stringify(r2)}`)
    const renewed = await a.renew(120_000)
    if (renewed.expiresAt <= r1.lock.expiresAt) throw new Error('renew did not extend the lock')
    await a.release()
    if ((await a.read()) !== null) throw new Error('lock file still there after release')
    const r3 = await b.acquire({ ttlMs: 1 })
    if (r3.kind !== 'acquired') throw new Error(`B could not acquire after release: ${JSON.stringify(r3)}`)
    await new Promise((resolve) => setTimeout(resolve, 50))
    const r4 = await a.acquire({ ttlMs: 60_000 })
    if (r4.kind !== 'held' || !r4.expired) throw new Error(`A should see B's expired lock: ${JSON.stringify(r4)}`)
    const r5 = await a.acquire({ ttlMs: 60_000, breakExpired: true })
    if (r5.kind !== 'acquired') throw new Error(`A could not break the expired lock: ${JSON.stringify(r5)}`)
    await a.release()
    const dir = await client.findChild(layout!.graphFolderId, '.gdsync', true)
    const left = dir ? (await client.listChildren(dir.id, 'files')).filter((f) => f.name === LOCK_FILE) : []
    if (left.length !== 0) throw new Error(`${left.length} lock file(s) left behind`)
    return 'acquired, contended, renewed, released, expired lock broken, no lock file left'
  })

  step('trash', async () => {
    await client.trash(mdFile!.id)
    if (!(await client.getFile(mdFile!.id)).trashed) throw new Error('file not trashed')
    const tree = await client.listTree(layout!.graphFolderId)
    if (tree.some((e) => e.file.id === mdFile!.id)) throw new Error('trashed file still listed')
    return 'trashed file is flagged and gone from the listing'
  })

  step('cleanup: delete the smoke root folder', async () => {
    await client.deleteForever(layout!.rootId)
    rootCreated = false
    try {
      await client.getFile(layout!.rootId)
      throw new Error('root folder still exists after delete')
    } catch (err) {
      if (!isNotFound(err)) throw err
    }
    return `"${rootName}" and everything under it deleted (404 confirmed)`
  })

  let passed = 0
  for (let i = 0; i < steps.length; i++) {
    const [name, run] = steps[i]
    deps.onStep(name, i + 1, steps.length)
    const t = Date.now()
    try {
      const detail = await run()
      passed++
      log(`smoke ${i + 1}/${steps.length} ok (${Date.now() - t} ms): ${name} — ${detail}`)
    } catch (err) {
      const error = describeGoogleError(err)
      log(`smoke ${i + 1}/${steps.length} FAILED: ${name} — ${error}`, err)
      return { passed, total: steps.length, failedStep: name, error, leftoverFolder: rootCreated ? rootName : null, durationMs: Date.now() - startedAt }
    }
  }
  log(`smoke passed ${passed}/${steps.length} in ${Date.now() - startedAt} ms with ${requestCount} requests`)
  return { passed, total: steps.length, failedStep: null, error: null, leftoverFolder: null, durationMs: Date.now() - startedAt }
}
